[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-ObjC"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-ObjC"]

[target.aarch64-apple-ios]       # if you also build for iOS / visionOS
rustflags = ["-C", "link-arg=-ObjC"]
