# Windows: Use static CRT to match webrtc-sys prebuilt binaries
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-ObjC"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-ObjC"]

[target.aarch64-apple-ios]       # if you also build for iOS / visionOS
rustflags = ["-C", "link-arg=-ObjC"]

[registries.crates-io]
protocol = "sparse"
